export const loadsConfig =  [{
  pickupDate: "",
  truckId: "",
  driverName: "",
  driverId: 0,
  loadNumber: "",
  brokerName: "",
  brokerId: 0,
  shipper:"",
  consignee:"",
  pickUpCityState: "",
  dropOffCityState: "",
  pickUpAddress: "",
  dropOffAddress: "",
  payment: 0,
  loadedMiles: 0,
  emptyMiles: 0,
  mileage: 0,
  dollarPerMile: 0,
  fuelCost: 0,
  driverPay: 0,
  dispatchFee: 0,
  lumper: 0,
  cancelFeeIncome: 0,
  detention: 0,
  detentionDriverPay: 0,
  secondStopDriverPay: 0,
  lateFee: 0,
  toll: 0,
  roadMaintenance: 0,
  otherExpenses: 0,
  totalExpenses: 0,
  profit: 0,
  commodity: "",
  weight: 0,
  trailer: "",
  confirmFilePath: ""
}]

export const loadsTextFields = [
  "pickupDate",
  "driverName",
  "loadNumber",
  "brokerName",
  "shipper",
  "consignee",
  "pickUpCityState",
  "dropOffCityState",
  "pickUpAddress",
  "dropOffAddress",
  "commodity",
  "trailer",
  "confirmFilePath"
]

export const loadsNumberFields = [
  "weight",
  "payment",
  "loadedMiles",
  "emptyMiles",
  "mileage",
  "dollarPerMile",
  "fuelCost",
  "driverPay",
  "dispatchFee",
  "lumper",
  "detention",
  "detentionDriverPay",
  "secondStopDriverPay",
  "lateFee",
  "toll",
  "roadMaintenance",
  "cancelFeeIncome",
  "otherExpenses",
  "totalExpenses",
  "profit",
]

export const loadsMandatoryFields = ['pickupDate', 'truckId', 'driverName', 'driverId','loadNumber', 'brokerName',
'brokerId','pickUpCityState', 'dropOffCityState', 'pickUpAddress', 'dropOffAddress', 'payment',
'mileage', 'fuelCost', 'driverPay', 'totalExpenses']




